# Generated by Django 3.2.25 on 2024-06-13 04:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_users_user_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
